- name: Create LoadBalancer Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: azure-vote-front
        namespace: "{{ namespace_name }}"
      spec:
        type: LoadBalancer
        selector:
          app: azure-vote-front
        ports:
          - port: 80
